### ISSUE TITLE
Constants greater than 0x7FFFFFFF

### ISSUE THREAD

**Issue by Exopandora** [SRAhub/MinimaxSimulator#20]
Due to the implementation it is not possible to create a constant using the full 32 bits (0xFFFFFFFF or ‭4294967295).
The maximum is instead limited to 0x7FFFFFFF or 2147483647 (Integer.MAX_VALUE).

**Comment by prohde** [comment]
You can use a constant with all 32 bits being 1. But due to the use of the two's complement the maximum positive (decimal) value is 2147483647.

**Comment by Exopandora** [comment]
I know this but you cant enter such a value

**Comment by prohde** [comment]
Actually this is true. I will fix this asap.

Try this as a workaround until I have fixed this issue:
1. enter 0x7FFFFFFF
2. press the button with the upwards arrow
3. delete all digits but a single one
4. press enter
5. save the constant value

Following the instructions above I was able to use 0xFFFFFFFF as a constant and save and load the project correctly.

**Comment by prohde** [comment]
Could you please confirm that your issue has been fixed with commit 94c7ca2 from branch constants-larger-than-0x7FFFFFFF?

**Comment by Exopandora** [comment]
The hex textfield ist fixed but you still cannot type in a negative decimal value without using the arrow keys.

**Comment by prohde** [comment]
Actually this was intended due to the update of the other spinner. But because it seems that it is wanted to be able to enter the minus sign as single character I made this possible in 87a84bb.

Therefore I think the issue is solved now. I am planning to release a new version of the simulator soon.
